INSERT INTO course (name) VALUES
('Language Arts'),
('Mathematics'),
('Science'),
('Health'),
('Basic Math'),
('Pre-algebra'),
('Consumer Math'),
('Algebra'),
('Geometry');

INSERT INTO student (name, email) VALUES
('Lucienne Greenholt','bernie.damore@gmail.com'),
('Adolf Jakubowski','jerrold.kerluke@rowe.com'),
('Shana VonRueden','jodie26@hotmail.com'),
('Adele Gleason','ritchie.seamus@gmail.com'),
('Audie Kilback','lhomenick@yahoo.com'),
('Bradly Lemke','ziemann.janelle@medhurst.com'),
('Leda Bednar','nicolas.dubuque@hotmail.com'),
('Maurice Wilderman','kassulke.elsie@hotmail.com'),
('Brittany Ziemann I','olebsack@oreilly.com'),
('Michele Schulist','zmohr@gmail.com'),
('Leslie DuBuque','brekke.kaylin@oconnell.com'),
('Emilie Prohaska MD','lebsack.alyce@gulgowski.com'),
('Jesus Ziemann','hgutmann@dare.info'),
('Dr. Thelma Harber','fblick@yahoo.com'),
('Lonny Stoltenberg','iferry@tromp.biz'),
('Annette Hansen','pcartwright@hahn.org'),
('Kole Brakus','erna47@yahoo.com'),
('Dr. Santiago Keeling','germaine76@yahoo.com'),
('Ms. Genevieve Fisher','barrows.arianna@yahoo.com'),
('Mrs. Alaina Jaskolski','bettye25@ratke.com'),
('Hassan Reilly','ewatsica@gmail.com'),
('Domenick Casper','leannon.janessa@trantow.com'),
('Randall Morissette','eliane82@fisher.info'),
('Verda Wiegand','wbode@huels.com'),
('Adella Price','erdman.amani@buckridge.com'),
('Kenna Willms','sbins@gmail.com'),
('Braden Kozey','juanita28@tromp.net'),
('Jefferey Wisozk','shanahan.candice@hahn.net'),
('Hattie Jaskolski Sr.','rbotsford@gmail.com'),
('Nico Torp','nlangworth@stanton.com'),
('Mrs. Leann Morar','watsica.shanel@yahoo.com'),
('Alejandrin Kautzer','stiedemann.magali@gmail.com'),
('Dino Orn','breinger@yahoo.com'),
('Ismael Kuvalis V','marilie.rosenbaum@hotmail.com'),
('Kraig Johns','jerrold26@russel.org'),
('Kaelyn Schulist','quinten05@quigley.com'),
('Carolyn OReilly','lhintz@konopelski.org'),
('Santino Parisian','julie18@schultz.net'),
('Nicholas Hammes','junior27@swaniawski.com'),
('Kimberly Cummerata','susan.bashirian@rau.org'),
('Lucie Mitchell','xschoen@ledner.com'),
('Quincy Tremblay','dalton84@macejkovic.com'),
('Jennyfer Marquardt','nikolaus.grady@grady.info'),
('Dr. Felicita Buckridge','blynch@keeling.com'),
('Carol Dicki IV','margaretta.moen@gmail.com'),
('Bert Hagenes Sr.','watson.kunde@bednar.info'),
('Guido Grady','herta60@wisozk.biz'),
('Anjali Donnelly','gmitchell@gmail.com'),
('Corene Waelchi PhD','bernice.sauer@gmail.com'),
('Lauretta Jerde','keanu01@gmail.com'),
('Mr. Granville Keebler','wilkinson.frida@bode.com'),
('Kali Reynolds MD','brook.cole@gmail.com'),
('Helmer Padberg','olind@hotmail.com'),
('Dr. Jamal Braun','ullrich.alexandrea@yahoo.com'),
('Michele Kiehn','bernadine.gutkowski@pfeffer.org'),
('Mr. Fausto Herman','oconner.jett@yahoo.com'),
('Carley Robel MD','randall97@hotmail.com'),
('Clifton Ferry','werner.hermann@spinka.com'),
('Mrs. Claudia Dickinson','makenna.maggio@hotmail.com'),
('Tommie Bins Sr.','noe.pacocha@hotmail.com'),
('Coralie McClure','alexie60@gmail.com'),
('Tara Botsford','keeling.alisha@hotmail.com'),
('Loren Parker','nader.delfina@sanford.biz'),
('Keagan Torp III','xmuller@will.com'),
('Kayden Heaney','victor.gutkowski@koss.info'),
('Axel Okuneva Jr.','molly81@lakin.com'),
('Dr. Zachary Balistreri','ireilly@hotmail.com'),
('Beau Walker','dasia.reynolds@gmail.com'),
('Niko OConnell','owen.homenick@hotmail.com'),
('Onie Hoppe II','rodrick.huel@reilly.net'),
('Randy Bradtke','rosenbaum.abelardo@hotmail.com'),
('Kali Metz','reina39@gmail.com'),
('Mrs. Kallie Osinski','angelina.stark@hotmail.com'),
('Elijah Rogahn','rogahn.rosalinda@denesik.com'),
('Cierra Effertz II','albert.mante@walker.com'),
('Mae Lang','conn.colton@yahoo.com'),
('Maribel Moen','worn@braun.org'),
('Dr. Devonte Schinner','lucie.upton@herman.com'),
('Melissa Barrows','amy85@gmail.com'),
('Eloise Ortiz','pearline.jakubowski@yahoo.com'),
('Jefferey Ernser','boconner@yahoo.com'),
('Darion Grant','maxine.dooley@gmail.com'),
('Declan Bergstrom','lratke@gmail.com'),
('Bart Miller PhD','arianna46@yahoo.com'),
('Treva Parker','jhagenes@braun.com'),
('Rafaela Kozey','bailey.trisha@yahoo.com'),
('Ruby Spencer','lbailey@pollich.com'),
('Sandy Kunde','gerry38@gmail.com'),
('Mrs. Adella Lindgren','mariane.jast@hotmail.com'),
('Dedric Mayer','ibrahim52@heidenreich.com'),
('Otho Orn','akeem91@collier.com'),
('Doyle Schowalter','ypaucek@yahoo.com'),
('Kole Rosenbaum','fbrekke@hotmail.com'),
('Malcolm Padberg','yundt.warren@gmail.com'),
('Emma Fahey','haskell.yost@schultz.net'),
('Jacynthe Wehner MD','fabiola.rice@gmail.com'),
('Ian Keebler','anais76@rath.biz'),
('Tiara Jaskolski','beth90@yahoo.com'),
('Maritza Wolf MD','esmitham@beer.com'),
('Rosalia Quigley','jeramy30@yahoo.com');

INSERT INTO student_course (student_id, course_id) VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(2,2),
(3,2),
(4,2),
(5,2),
(6,2),
(7,2),
(8,2),
(9,2),
(10,2),
(11,2),
(12,2),
(13,2),
(14,2),
(15,2),
(16,2),
(17,2),
(18,2),
(19,2),
(20,2),
(21,2),
(22,2),
(23,2),
(24,2),
(25,2),
(26,2),
(27,2),
(28,2),
(29,2),
(30,2),
(31,2),
(32,2),
(33,2),
(34,2),
(35,2),
(36,2),
(37,2),
(38,2),
(39,2),
(40,2),
(41,2),
(42,2),
(43,2),
(44,2),
(45,2),
(46,2),
(47,2),
(48,2),
(49,2),
(50,2),
(51,2);